services:
  backend:
    build: ./backend
    ports:
      - "8010:8010"
    volumes:
      - ./backend:/app
    networks:
      - simnet

  frontend:
    build: ./frontend
    ports:
      - "8009:8009"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - simnet

networks:
  simnet:
    driver: bridge
